config/routes.rb
Bountyboard::Application.routes.draw do

  root 'bounties#index'

  resources :artists
  resources :bounties
  resources :candidacies
  resources :votes
  resources :favorites

  match '/auth/:provider/callback', to: 'sessions#create', via: :get
  match '/sign_out', to: 'sessions#destroy', via: :delete, via: :post
  match '/auth/failure', to: 'sessions#auth_failure', via: :get
end

app/models/artist.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  email         :text             not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  rememberToken :string(255)
#  type          :string(255)
#  bio           :text             default(""), not null
#  bounty_rules  :text             default(""), not null
#  approved      :boolean          default(FALSE), not null
#  admin         :boolean          default(FALSE), not null
#  active        :boolean
#

class Artist < User

  # Relationships ==============================================================
  has_many :candidacies, :inverse_of => :artist
  has_many :bounties, :through => :candidacies

  # Validations ================================================================
  validates :bio, presence: true
  validates :bounty_rules, presence: true
  validates :approved, :inclusion => {:in => [true, false]}
  validates :active, :inclusion => {:in => [true, false]}

  # The "name" property is optional for users but required for artists
  validates :name, presence: true
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  include SessionsHelper
  # require 'sanitize'

  # Display a list of all artists in the system, with links to see their
  # individual profiles.
  def index
    @artist = Artist.all
  end

  # Display an individual artist's profile.
  def show
    @artist = Artist.find(params[:id])
    acceptingCandidacies = Candidacy.where(
      'artist_id=? AND (accepted_at IS NOT NULL)',  @artist.id
    )
    @acceptedBounties = []
    @completedBounties = []
    acceptingCandidacies.each do |c|
      if c.bounty.status == "Completed"
        @completedBounties.append(c.bounty)
      else
        @acceptedBounties.append(c.bounty)
      end
    end
  end

  # Display the form to create a new artist. Only admins may perform this
  # action.
  def new
    unless signed_in?
      flash[:error] = "You must sign in."
      redirect_to root_path
    end
    if currentUser.admin?
      @artist = Artist.new
    else
      flash[:error] = "Only administrators can create new artists."
      redirect_to root_path
    end
  end

  # Create a new artist. Only admins may perform this action.
  def create
    unless signed_in?
      flash[:error] = "You must sign in."
      redirect_to root_path
    end
    if currentUser.admin?
      #TODO Figure out how approved fits into our workflow.
      params[:artist][:approved] = true
      params[:artist][:active] = true

      # Sanitize the name, bio, and bounty_rules fields for artists.
      # Clean name of all HTML, clean the rest using "Relaxed" method which
      # allows:
      #
      # "Allows an even wider variety of markup than BASIC, including images and
      # tables. Links are still limited to FTP, HTTP, HTTPS, and mailto
      # protocols, while images are limited to HTTP and HTTPS. In this mode,
      # rel="nofollow" is not added to links."

      params[:artist][:name] = Sanitize.clean(params[:artist][:name])
      params[:artist][:bio] = Sanitize.clean(params[:artist][:bio], Sanitize::Config::RELAXED)
      params[:artist][:bounty_rules] = Sanitize.clean(params[:artist][:bounty_rules], Sanitize::Config::RELAXED)

      @artist = Artist.new(artist_create_params)
      if @artist.save
        flash[:notice] = "Artist created successfully!"
        redirect_to root_path
      else
        flash[:error] = "Error saving artist."
        render 'new'
      end
    else
      flash[:error] = "Only administrators can create new artists."
      redirect_to root_path
    end
  end

  # Display the edit form for the currently logged in artist or for an
  # administrator.
  def edit
    unless signed_in?
      redirect_to root_path, :error => "You must sign in."
    end
    @artist = Artist.find(params[:id])
    unless (@artist == currentUser || currentUser.admin?)
      flash[:error] = "You are not authorized to edit this artist."
      redirect_to root_path
    end
  end

  # Update the currently logged in artist. Admins are allowed to update artist
  # properties.
  def update
    unless signed_in?
      flash[:error] = "You must sign in."
      redirect_to root_path
    end
    @artist = Artist.find(params[:id])
    unless (@artist == currentUser || currentUser.admin?)
      flash[:error] = "You are not authorized to edit this artist."
      redirect_to root_path
    end
    # Sanitize the name, bio, and bounty_rules fields for artists.
    # Clean name of all HTML, clean the rest using "Relaxed" method which
    # allows:
    #
    # "Allows an even wider variety of markup than BASIC, including images and
    # tables. Links are still limited to FTP, HTTP, HTTPS, and mailto
    # protocols, while images are limited to HTTP and HTTPS. In this mode,
    # rel="nofollow" is not added to links."

    params[:artist][:name] = Sanitize.clean(params[:artist][:name])
    params[:artist][:bio] = Sanitize.clean(params[:artist][:bio], Sanitize::Config::RELAXED)
    params[:artist][:bounty_rules] = Sanitize.clean(params[:artist][:bounty_rules], Sanitize::Config::RELAXED)
    if @artist.update_attributes(artist_update_params)
      flash[:notice] = "Artist updated!"
      redirect_to root_path
    else
      flash[:error] = "Error updating artist."
      redirect_to root_path
    end
  end

  # Artists may not be deleted. Instead, an "active" property is set to false,
  # prventing an artist from participating in the system or being selected for
  # bounties.
  def destroy
    unless signed_in?
      flash[:error] = "You must sign in."
      redirect_to root_path
    end
    @artist = Artist.find(params[:id])
    if currentUser.admin?
      @artist.active = false
      if @artist.save
        flash[:notice] = "Artist #{@artist.name} is now inactive!"
        redirect_to root_path
      else
        flash[:error] = "Error deactivating artist."
        redirect_to root_path
      end
    else
      flash[:error] = "Only administrators can delete artists."
      redirect_to root_path
    end
  end

  private

    def artist_create_params
      params.require(:artist).permit(
        :name,
        :email,
        :bio,
        :bounty_rules
      )
    end

    def artist_update_params
      permitted_keys = [
        :name,
        :email,
        :bio,
        :bounty_rules,
        :active
      ]
      # admins can approve or un-approve an artist
      if currentUser.admin?
        permitted_keys.concat([
          :approved
        ])
      end
      params.require(:artist).permit(permitted_keys)
    end

end

app/views/artists/edit.html.erb
<div id="form-area">
  <%= render 'shared/error_messages' %>
  <%= semantic_form_for @artist do |artist_form| %>
      <%= artist_form.input :name, :required => true %>
      <%= artist_form.input :email, :required => true %>
      <%= artist_form.input :bio, :as => :ckeditor, :input_html => { :ckeditor => { :height => 400, :width => 800 }}, :required => true %>
      <%= artist_form.input :bounty_rules, :as => :ckeditor, :input_html => { :ckeditor => { :height => 400, :width => 800 }} :required => true %>
      <% if currentUser.admin? %>
        <%= artist_form.input :approved%>
        <%= artist_form.input :active%>
      <% end %>
      <div class="control-panel"><%= artist_form.submit :class => "bounty-button submit-button" %><%=   link_to 'Back', artist_path(@artist.id), class: 'bounty-button' %></div>
  <% end %>
</div>

app/views/artists/index.html.erb
<div id="artist-list">
  <ul>
  <% @artist.each do |a| %>
      <li><%= link_to a.name, artist_path(a.id) %></li>
  <% end %>
  </ul>
</div>

app/views/artists/new.html.erb
<div id="form-area">
    <%= render 'shared/error_messages' %>
    <%= semantic_form_for @artist do |artist_form| %>
        <%= artist_form.input :name, :required => true %>
        <%= artist_form.input :email, :required => true %>
        <%= artist_form.input :bio, :as => :ckeditor, :input_html => { :ckeditor => { :height => 400, :width => 800 }}, :required => true %>
        <%= artist_form.input :bounty_rules, :as => :ckeditor, :input_html => { :ckeditor => { :height => 400, :width => 800 }}, :required => true %>
        <div class="control-panel"><%= artist_form.submit :class => "bounty-button submit-button" %><%=   link_to 'Back', root_path, class: 'bounty-button' %></div>
    <% end %>
</div>

app/views/artists/show.html.erb
<div id="artist-show">
  <div class="header">Artist Details</div>
    <div class="content-left">
      <ul>
        <li class="subheader">Name</li>
        <li class="profile-data"><%= @artist.name %> <%= @artist.email %></li>
        <li class="subheader">Biography</li>
        <li class="profile-data"><%= @artist.bio.html_safe %></li>
        <li class="subheader">Bounty Rules</li>
        <li class="profile-data"><%= @artist.bounty_rules.html_safe %></li>
      </ul>
    </div>
    <div class="content-right">
      <div class="join-date"><%= @artist.created_at.to_s(:joined_on) %></div>
    </div>

  <div class="bounty-wrapper">
    <div class="header"><%= @artist.name %> is currently working on...</div>
      <% unless @acceptedBounties.empty? %>
        <div class="button-wrapper">
          <% @acceptedBounties.each do |b| %>
            <%=   link_to "#{b.name}", bounty_path(b.id), class: 'bounty-button' %>
          <% end %>
        </div>
      <% else %>
        <h2>Nothing!</h2>
      <% end %>

     <div class="header"><%= @artist.name %>'s Completed Bounties</div>
      <% unless @completedBounties.empty? %>
        <div class="button-wrapper">
          <% @completedBounties.each do |b| %>
            <%=   link_to "#{b.name}", bounty_path(b.id), class: 'bounty-button' %>
          <% end %>
        </div>
      <% else %>
         <h2><%= @artist.name %> hasn't completed any bounties!</h2>
      <% end %>
    </div>

  <div class="control-panel">
    <%=   link_to 'Back', root_path, class: 'bounty-button' %>
    <% if signed_in? %>

      <% if (@artist == currentUser) || currentUser.admin? %>
        <%=   link_to 'Update', edit_artist_path(@artist.id, "Edit"), class: 'bounty-button' %>
      <% end %>

      <% if currentUser.admin? %>
        <%=   link_to 'Delete', @artist, :confirm => "Are you sure you want to delete #{@artist.name}?", :method => :delete, class: 'bounty-button' %>
      <% end %>

      <% if currentUser.admin? %>
        <%=   link_to 'Approve', artist_path(:artist => {:approved => true}), :method => :put, :confirm => "Are you sure you want to approve this artist?", class: 'bounty-button' %>
      <% end %>
    <% end %>
  </div>
</div>