config/routes.rb
Bountyboard::Application.routes.draw do

  root 'bounties#index'

  resources :artists
  resources :bounties
  resources :candidacies
  resources :votes
  resources :favorites

  match '/auth/:provider/callback', to: 'sessions#create', via: :get
  match '/sign_out', to: 'sessions#destroy', via: :delete, via: :post
  match '/auth/failure', to: 'sessions#auth_failure', via: :get
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController

  include SessionsHelper
  include VotesHelper
  require 'sanitize'

  respond_to :json, :html

  def self.BOUNTIES_PER_PAGE
    40
  end

  # Display a list of all bounties in the system, with links to see their
  # individual bounties.
  def index
    @bounties = Bounty
      .viewable_by(currentUser)
      .page(params[:page]).per(BountiesController.BOUNTIES_PER_PAGE)

    # apply filters from the user

    # default filter values
    filters =  {
      :price_min => nil,
      :price_max => nil,
      :adult => "kid-friendly",
      :own => nil,
      :may_accept => nil,
      :status => nil,
    }.with_indifferent_access

    filters.merge!(params)

    if filters[:price_min]
      @bounties = @bounties.price_greater_than params["price_min"].to_f
    end
    if filters[:price_max]
      @bounties = @bounties.price_less_than params["price_max"].to_f
    end
    if filters[:adult] == "adult"
      @bounties = @bounties.only_adult_content
    elsif filters[:adult] == "kid-friendly"
      @bounties = @bounties.no_adult_content
    end
    if filters[:own] && currentUser
      @bounties = @bounties.owned_by currentUser
    end
    if filters[:may_accept] && currentUser.is_a?(Artist)
      @bounties = @bounties.may_accept currentUser
    end
    if filters[:status]
      @bounties = @bounties.only_status(filters[:status])
    end

    respond_with @bounties.to_a.sort { |bounty| -bounty.score }
  end

  # Display an individual bounty.
  def show
    @bounty = Bounty.find(params[:id])
    if !@bounty.viewable_by?(currentUser)
      flash[:error] = "That bounty is private."
      redirect_to root_path
    end
  end

  # Display the form to create a new bounty. Anyone may perform this action.
  def new
    unless signed_in?
      flash[:error] = "You must sign in."
      redirect_to root_path
    end
    @bounty = Bounty.new
  end

  # Create a new bounty. Anyone may perform this action.
  def create
    unless signed_in?
      flash[:error] = "You must sign in."
      redirect_to root_path
    end

    # If no specific artists were selected. Then create a candidacy to all
    # active artists.
    if !params[:bounty][:artist_ids] || params[:bounty][:artist_ids] == [""]
	  params[:bounty][:artist_ids] = Artist.where(:active => true).pluck(:id)
    end

    # Sanitize the name and description fields for bounties. Clean name of all
    # HTML, clean descs using "Relaxed" method which allows:
    #
    # "Allows an even wider variety of markup than BASIC, including images and
    # tables. Links are still limited to FTP, HTTP, HTTPS, and mailto protocols,
    # while images are limited to HTTP and HTTPS. In this mode, rel="nofollow"
    # is not added to links."

    params[:bounty][:name] = Sanitize.clean(params[:bounty][:name])
    params[:bounty][:name] = Sanitize.clean(params[:bounty][:tag_line])
    params[:bounty][:desc] = Sanitize.clean(params[:bounty][:desc], Sanitize::Config::RELAXED)

    @bounty = Bounty.new(bounty_create_params)
    @bounty.owner = currentUser

    if @bounty.save
      flash[:notice] = "Bounty created successfully!"
      redirect_to root_path
    else
      flash[:error] = "Error saving bounty."
      render 'new'
    end
  end

  # Display the edit form for the bounty. Artists that are candidates for the
  # bounty may use this for completion of a bounty. Owners of the bounty
  # may edit all other properties.
  def edit
    unless signed_in?
      flash[:error] = "You must sign in."
      redirect_to root_path
    end
    @bounty = Bounty.find(params[:id])
    # The format parameter is a string passed along with the id when using
    # bounty_path. Ex. bounty_path(4, "Complete") would set @format to
    # "Complete", which the view will use to render the form for Completing a
    # bounty, maintaining REST.
    @format = params[:format]
    unless (@bounty.owner == currentUser || @bounty.artists.include?(currentUser))
      flash[:error] = "You are not authorized to edit this bounty."
      redirect_to root_path
    end
  end

  # Update the bounty. Artists that are candidates for the bounty may use this
  # for completion of a bounty. Owners of the bounty may edit all other
  # properties.
  def update
    unless signed_in?
      flash[:error] = "You must sign in."
      redirect_to root_path
    end
    @bounty = Bounty.find(params[:id])
    unless (@bounty.owner == currentUser || @bounty.artists.include?(currentUser))
      flash[:error] = "You are not authorized to edit this bounty."
      redirect_to root_path
    end
    if params[:bounty][:url]
      @bounty.artwork_from_url(params[:bounty][:url])
      if @bounty.update_attributes(bounty_update_params)
        flash[:notice] = "Bounty Completed!"
        redirect_to root_path
      else
        flash[:error] = "Error completing bounty."
        redirect_to root_path
      end
    else
      # Sanitize the name and description fields for bounties. Clean name of all
      # HTML, clean descs using "Relaxed" method which allows:
      #
      # "Allows an even wider variety of markup than BASIC, including images and
      # tables. Links are still limited to FTP, HTTP, HTTPS, and mailto protocols,
      # while images are limited to HTTP and HTTPS. In this mode, rel="nofollow"
      # is not added to links."
      params[:bounty][:name] = Sanitize.clean(params[:bounty][:name])
      params[:bounty][:name] = Sanitize.clean(params[:bounty][:tag_line])
      params[:bounty][:desc] = Sanitize.clean(params[:bounty][:desc], Sanitize::Config::RELAXED)

      if @bounty.update_attributes(bounty_update_params)
        flash[:notice] = "Bounty Updated!"
        redirect_to root_path
      else
        flash[:error] = "Error updating bounty."
        redirect_to root_path
      end
    end
  end

  # Delete the bounty. Admins may delete any bounty. But the bounty's owner may
  # only do this if the bounty is unclaimed.
  def destroy
    unless signed_in?
      flash[:error] = "You must sign in."
      redirect_to root_path
    end
    @bounty = Bounty.find(params[:id])

    if (@bounty.owner == currentUser && (@bounty.status == 'Unclaimed')) || currentUser.admin?
      if Bounty.destroy(params[:id])
        flash[:notice] = "Bounty successfully removed!"
        redirect_to root_path
      else
        flash[:error] = "Error removing bounty."
        redirect_to root_path
      end
    else
      if @bounty.owner != currentUser
        flash[:error] = "You are not authorized to remove this bounty."
        redirect_to root_path
      elsif @bounty.status == "Accepted"
        acceptor = @bounty.acceptor_candidacy.artist.get_identifier
        flash[:error] = "This bounty is being worked on by #{acceptor} and cannot be deleted."
        redirect_to root_path
      else
        flash[:error] = "This bounty is #{@bounty.status} and cannot be deleted."
        redirect_to root_path
      end
    end
  end

  private

    def bounty_create_params
      params.require(:bounty).permit(
        :name,
        :desc,
        :price_cents,
        :price_currency,
        :adult_only,
        :private,
        :complete_by,
        :tag_line
      )
    end

    def bounty_update_params(bounty)
      permitted_keys = [
        :name,
        :desc,
        :price_cents,
        :price_currency,
        :adult_only,
        :private,
        :complete_by,
        :tag_line
      ]
      # the acccepting artist can complete a bounty
      if bounty.accepting_candidacy && bounty.accepting_candidacy.artist == currentUser
        permitted_keys.concat([
          :url,
          :preview,
          :completed_at
        ])
      end
      params.require(:bounty).permit(permitted_keys)
    end

end

app/views/bounties/_showAll.erb
<% if @bounty %>
  <% @bounty.sort{|b,a| a.created_at <=> b.created_at}.each do |b| %>
    <% unless b.is_private %>
      <div class="span3 bounty-square">
      <div class="nail"></div>
      <div class="ribbon-wrapper"><div class="ribbon"><%= humanized_money_with_symbol b.price %></div></div>
        <div class="name"><%= b.name %></div>
        <div class="candidates">
          <% b.candidacies.each do |c| %>
            <div id="<%= c.artist.get_identifier %>"></div>
          <% end %>
        </div>
        <div class="short-desc">
          <%= b.desc %>
          <div class="read-more"><%=   link_to 'Read More', bounty_path(b.id), class: 'btn btn-primary' %>
            <% if b.owner == currentUser %>
              <%=   link_to 'Delete', b, :confirm => "Are you sure you want to delete #{b.name}?", :method => :delete, class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/bounties/_show_artist_list.erb
<% if @artist %>
  <% @artist.each do |a| %>
    <%= link_to a.name, artist_path(a.id) %>
  <% end %>
  <br>
<% end %>

app/views/bounties/edit.html.erb
<div id="form-area">
  <%= render 'shared/error_messages' %>
  <% if (@format == "Edit") %>
    <%= semantic_form_for @bounty do |bounty_form| %>
        <%= bounty_form.input :name, :required => true, :hint => "The name of your bounty." %>
        <%= bounty_form.input :tag_line, :required => true, :hint => "A short description of your bounty for the front page. Max 160 characters.", :label => "Tag Line" %>
        <%= bounty_form.input :desc, :as => :ckeditor, :input_html => { :ckeditor => { :height => 400, :width => 800 }}, :label => "Description", :required => true, :hint => "Enter a detailed description of your bounty. References help!" %>
        <%= bounty_form.input :price, :required => true, :hint => "The price you're willing to pay. Min $5.00 USD" %>
        <%= bounty_form.input :private, :required => false, :as => :select, :hint => "If a bounty is private, only the artists you pick and admins may see it." %>
        <%= bounty_form.input :complete_by, :as => :date_select, :start_year => Time.now.year, :label => "Due Date", :required => false, :hint => "The date by which this bounty must be finished. (Optional)" %>
        <%= bounty_form.input :artists, :collection => Artist.where(:active => true, :approved => true), :as => :check_boxes, :input_html => { :checked => 'checked' }, :hint => "Which artists may complete your bounty?"%>
        <%= bounty_form.input :moods, :as => :check_boxes, :hint => "Tags that help describe your bounty at a glance. Min 1. Max 2."%>
      <div class="control-panel"><%= bounty_form.submit :class => "bounty-button submit-button" %><%=   link_to 'Back', bounty_path(@bounty.id), class: 'bounty-button' %></div>
    <% end %>
  <% elsif (@format == "Complete") %>
    <%= semantic_form_for @bounty do |bounty_form| %>
      <%= bounty_form.input :url, :as => :string, :required => true, :hint => "Enter a URL where the artwork can be found." %>
      <%= bounty_form.input :preview, :as => :file, :required => false, :hint => "You may submit a thumbnail for this artwork to be displayed on the front page. Must be 200x280px. (Optional)" %>
      <div class="control-panel"><%= bounty_form.submit :class => "bounty-button submit-button" %><%=   link_to 'Back', bounty_path(@bounty.id), class: 'bounty-button' %></div>
    <% end %>
  <% end %>
</div>

app/views/bounties/index.html.erb
<div id="bounty-wrapper">
  <%= link_to_previous_page @bounties, 'Previous', class: 'pagination previous' %><%= link_to_next_page @bounties, 'Next', class: 'pagination next' %>
  <div id="bounty-list">
    <% @bounties.each do |b| %>
    <div
      class="bounty-square"
      data-price="<%= b.price %>"
      data-id="<%= b.id %>"
    >
        <%=   link_to content_tag(:span, ""), bounty_path(b.id), class: 'bounty-click-wrapper' %>
        <% if b.status == "Completed" %>
          <% if b.preview_file_name %>
            <%= image_tag("#{b.preview.url(:standard)}") %>
          <% else %>
            <%= image_tag("#{b.artwork.url(:thumb)}") %>
          <% end %>
        <% else %>
          <div class="nail"></div>
          <div class="name"><%= b.name %></div>
          <div class="price-ribbon"><div><%= humanized_money_with_symbol b.price %></div></div>
          <div class="short-desc hyphenate">
            <%= b.tag_line %>
          </div>
        <% end %>
        <% if signed_in? %>
            <% favorite = b.favored_by(currentUser) %>
            <% if favorite %>
              <%=  link_to '', favorite, :method => :delete, class: 'fav fav-red' %>
            <% else %>
              <%=  link_to '', favorites_path(:favorite, :bounty => b.id), :action => :create, :method => :post, class: 'fav' %>
            <% end %>
            <% if b.status == "Accepted" %>
              <div class="accepted-stamp"></div>
            <% end %>
            <% if b.status == "Completed" %>
              <div class="completed-stamp"></div>
            <% end %>
            <% if b.can_vote?(currentUser) %>
              <% cast_vote = b.vote_by(currentUser) %>
              <% if cast_vote %>
                <% if cast_vote.vote_type == VoteType::UPVOTE %>
                  <%=  link_to '', cast_vote, :method => :delete, class: 'upvote upvote-red' %>
                  <div class="downvote downvote-grey"></div>
                <% else %>
                  <div class="upvote upvote-grey"></div>
                  <%=  link_to '', cast_vote, :method => :delete, class: 'downvote downvote-red' %>
                <% end %>
              <% else %>
                <%=  link_to '', votes_path(:vote => {:vote_type => VoteType::UPVOTE}, :bounty => b.id), :action => :create, :method => :post, class: 'upvote' %>
                <%=   link_to '', votes_path(:vote => {:vote_type => VoteType::DOWNVOTE}, :bounty => b.id), :action => :create, :method => :post, class: 'downvote' %>
              <% end %>
            <% end %>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/bounties/new.html.erb
<div id="form-area" class="">
    <%= render 'shared/error_messages' %>
    <%= semantic_form_for @bounty do |bounty_form| %>
        <%= bounty_form.input :name, :required => true, :hint => "The name of your bounty. Max 40 characters." %>
        <%= bounty_form.input :tag_line, :required => true, :hint => "A short description of your bounty for the front page. Max 160 characters.", :label => "Tag Line" %>
        <%= bounty_form.input :desc, :as => :ckeditor, :input_html => { :ckeditor => { :height => 400, :width => 800 }}, :label => "Description", :required => true, :hint => "Enter a detailed description of your bounty. References help!"%>
        <%= bounty_form.input :price, :required => true, :hint => "The price you're willing to pay. Min $5.00 USD" %>
        <%= bounty_form.input :private, :required => false, :as => :select, :hint => "If a bounty is private, only the artists you pick and admins may see it." %>
        <%= bounty_form.input :complete_by, :as => :date_select, :start_year => Time.now.year, :label => "Due Date", :required => false, :hint => "The date by which this bounty must be finished. (Optional)" %>
        <%= bounty_form.input :artists, :collection => Artist.where(:active => true, :approved => true), :as => :check_boxes, :input_html => { :checked => 'checked' }, :hint => "Which artists may complete your bounty?"%>
        <%= bounty_form.input :moods, :as => :check_boxes, :hint => "Tags that help describe your bounty at a glance. Min 1. Max 2."%>
        <div class="control-panel"><%= bounty_form.submit :class => "bounty-button submit-button" %><%=   link_to 'Back', root_path, class: 'bounty-button' %></div>
<% end %>
</div>

app/views/bounties/show.html.erb
<div id="bounty-show">
  <div class="name">
    <%= @bounty.name %><br>
    <% if @bounty.adult_only %>
      <div class="adult">18+</div>
    <% end %>
  </div>
  <% if @bounty.status == "Unclaimed" %>
    <div class="candidacies">
      <% unless @bounty.candidacies.empty? %>
        <% @bounty.candidacies.each do |c| %>
          <%= c.artist.get_identifier %>
          <% unless c == @bounty.candidacies.last %>
          or
          <% end %>
        <% end %>
        may complete this bounty for <%= humanized_money_with_symbol @bounty.price %>
      <% else %>
        All artists have rejected this bounty. :(
      <% end %>
    </div>
  <% else %>
    <div class="status"><%= @bounty.status %> by <%= @bounty.acceptor_candidacy.artist.get_identifier %> for <%= humanized_money_with_symbol @bounty.price %></div>
  <% end %>

  <% if @bounty.status == "Completed" %>
   <a href=<%="#{@bounty.url}"%>><img src=<%="#{@bounty.url}"%> class="completed-art"></a>
  <% else %>
    <div class="desc hyphenate"><%= @bounty.desc.html_safe %></div>
    <div class="moods">
      |
      <% @bounty.moods.each do |m| %>
        <%= m.name %> |
      <% end %>
    </div>
  <% end %>
  <div class="dates">
    Created on <%= @bounty.created_at.strftime("%B %d %Y") %>
    <% if @bounty.status != "Unclaimed" %> | Accepted on <%= @bounty.acceptor_candidacy.accepted_at.strftime("%B %d, %Y") %><% end %>
    <% if @bounty.status == "Completed" %> | Completed on <%= @bounty.completed_at.strftime("%B %d, %Y") %><% end %>
    <% if @bounty.complete_by %><h3>This bounty must be finished by <%= @bounty.complete_by.strftime("%B %d, %Y") %></h3><% end %>
  </div>
  <div class="control-panel">
  <%=   link_to 'Back', root_path, class: 'bounty-button' %>
  <% if signed_in? %>
    <% if (@bounty.owner == currentUser && @bounty.status == 'Unclaimed') || currentUser.admin? %>
      <%=   link_to 'Update', edit_bounty_path(@bounty.id, "Edit"), class: 'bounty-button' %>
    <% end %>
    <% if (@bounty.owner == currentUser && @bounty.status == 'Unclaimed') || currentUser.admin? %>
      <%=   link_to 'Delete', @bounty, :confirm => "Are you sure you want to delete #{@bounty.name}?", :method => :delete, class: 'bounty-button' %>
    <% end %>
    <% if @bounty.artists.include?(currentUser) && @bounty.status == 'Unclaimed' %>
      <%=   link_to 'Accept', candidacy_path(:candidacy => {:accepted_at => DateTime.now}), :method => :put, :confirm => "Are you sure you want to accept this bounty?", class: 'bounty-button' %>
    <% end %>
    <% if @bounty.artists.include?(currentUser) && @bounty.status == 'Unclaimed' %>
      <%=   link_to 'Reject', candidacy_path, :method => :delete, :confirm => "Are you sure you want to reject this bounty?", class: 'bounty-button' %>
    <% end %>
    <% if @bounty.acceptor_candidacy && currentUser == @bounty.acceptor_candidacy.artist && @bounty.status == 'Accepted' %>
      <%=   link_to 'Complete', edit_bounty_path(@bounty.id, "Complete"), class: 'bounty-button' %>
    <% end %>
    <% if @bounty.acceptor_candidacy && currentUser == @bounty.acceptor_candidacy.artist && @bounty.status == 'Completed' %>
      <%=   link_to 'Update Artwork URL', edit_bounty_path(@bounty.id, "Complete"), class: 'bounty-button' %>
    <% end %>
 <% end %>
</div>