config/routes.rb
Bountyboard::Application.routes.draw do

  root 'bounties#index'

  resources :artists
  resources :bounties
  resources :candidacies
  resources :votes
  resources :favorites

  match '/auth/:provider/callback', to: 'sessions#create', via: :get
  match '/sign_out', to: 'sessions#destroy', via: :delete, via: :post
  match '/auth/failure', to: 'sessions#auth_failure', via: :get
end

app/views/layouts/_filters_controls.html.erb
<div id="dropdown-filters-controls" class="dropdown dropdown-tip">
  <div class="dropdown-panel">
    <div id="filter-control">
      <label for="filter-cost">Price:</label>
      <input id="filter-cost"
        data-bounty_min_price="<%= Bounty.MINIMUM_PRICE %>"
        data-bounty_max_price="<%= Bounty.MAXIMUM_PRICE %>"
        type="text"
      >
      <div id="filter-cost-widget" class="filters-slider"></div>
      <hr>
      <p>Age-Restricted Bounties</p>
      <div id="filter-adult" class="filter-buttonset">
        <label for="filter-adult-all">Show All</label><input id="filter-adult-all" type="radio" name="filter-adult" value="all"><label for="filter-adult-other">G-Rated Only</label><input id="filter-adult-other" type="radio" name="filter-adult" value="kid-friendly" checked><label for="filter-adult-only">Adult Only</label><input id="filter-adult-only" type="radio" name="filter-adult" value="adult">
      </div>
      <hr>
      <p>Bounty Status</p>
      <div id="filter-status" class="filter-buttonset">
        <label for="filter-status-all">All</label><input id="filter-status-all" type="radio" name="filter-status" value="" checked><label for="filter-status-unclaimed">Unclaimed</label><input id="filter-status-unclaimed" type="radio" name="filter-status" value="unclaimed"><label for="filter-status-accepted">In Progress</label><input id="filter-status-accepted" type="radio" name="filter-status" value="accepted"><label for="filter-status-completed">Complete</label><input id="filter-status-completed" type="radio" name="filter-status" value="completed">
      </div>
      <% if signed_in? %>
        <hr>
        <p>My Bounties</p>
        <div id="filter-ownership" class="filter-buttonset">
              <label for="filter-ownership-off">Show All</label><input id="filter-ownership-off" type="radio" name="filter-ownership" value="" checked><label for="filter-ownership-on">Only Bounties I Own</label><input id="filter-ownership-on" type="radio" name="filter-ownership" value="on">
        </div>
        <% if currentUser.is_a?(Artist) %>
          <hr>
          <p>Searching for Work?</p>
          <div id="filter-candidacy" class="filter-buttonset">
                <label for="filter-candidacy-off">Show All</label><input id="filter-candidacy-off" type="radio" name="filter-candidacy" value="" checked><label for="filter-candidacy-on">Only Bounties I Can Accept</label><input id="filter-candidacy-on" type="radio" name="filter-candidacy" value="on">
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-wrapper">
    &copy; Lionheart Studio, Nixie Bishop, and Brent Houghton, 2013<br>
    The Bounty Board is free software available under the open source AGPL
    license.
    <a href="http://github.com/lionheartstudio/bountyboard">Play with the source code.</a><br>
  </div>
</footer>

app/views/layouts/_header.html.erb
# encoding: UTF-8
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container-fluid">
			<%= link_to 'The Bounty Board', '#', class: 'brand' %>
			<nav class="nav-collapse collapse">
				<ul class="nav">
					<li class="dropdown">
						<%= link_to raw('About <b class="caret"></b>'), '#', class: 'dropdown-toggle', :'data-toggle' => 'dropdown' %>
						<ul class="dropdown-menu">
							<li><%= link_to 'The Bounty Board', '#' %></li>
							<li><a href="http://developer.mozilla.org/en-US/docs/Persona/Why_Persona">Persona (artist sign-in)</a></li>
						</ul>
					</li>
				</ul>
			</nav>
			<%= link_to 'Artist Sign-In with Persona', '#', class: 'btn pull-right' %>
		</div>
	</div>
</header>

app/views/layouts/_nav_bar.html.erb
<nav>
  <%= link_to 'The Bounty Board', root_path %>
  <%= link_to 'Show All Artists', artists_path %>
  <% if signed_in? && currentUser.admin? %>
    <%= link_to 'New Artist', new_artist_path %>
  <% end %>
  <% if signed_in? && currentUser.is_a?(Artist) %>
    <%= link_to 'Your Profile', artist_path(currentUser.id) %>
  <% end %>
  <% if controller_name == 'bounties' && action_name == 'index' %>
    <a data-dropdown="#dropdown-filters-controls" href="#">
      Filter Displayed Bounties
    </a>
  <% end %>
  <span class="login-notify-area">
    <% if signed_in? %>
          Logged in as
      <%= currentUser.get_identifier() %>
    <%  else %>
      <button class="persona-login-button">
        Sign In with Persona
      </button>
    <%  end %>
  </span>
</nav>

app/views/layouts/_persona_lib.html.erb
<%
# This partial provides JS libraries for implementing authentication with
# Persona. Include this partial in the page's head section, then insert the
# persona_form partial into the body HTML where you want the login form to be.
%>
<script src="https://browserid.org/include.js" type="text/javascript"></script>
<script type='text/javascript'>
	function loginViaEmail() {
		navigator.id.get(function(assertion) {
			if (assertion) {
				$('input[name=assertion]').val(assertion);
				$('#browser_id_form').submit();
			} else {
				window.location = "#{failure_path}"
			}
		});  
	}

	$(function() {
			$('#browser_id_form button').click(function() {
			loginViaEmail();
			return false;
		});
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Bounty Board</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script src="https://browserid.org/include.js" type="text/javascript"></script>
  <%= csrf_meta_tags %>

  <!-- provide HTML5 compatibility for IE 8 and older -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
  <div class="wrapper">
  <!--    Header navigation bar on the top of the page with sign-in controls. -->

    <%= render 'layouts/nav_bar' %>

    <header>
      <% if signed_in? %>
        <button class="bounty-button"><%=   link_to 'Post a Bounty', new_bounty_path, id: 'post-bounty' %></button>
      <%  else %>
        <button class="persona-login-button bounty-button">Sign In to Post Your Bounty</button>
      <%  end %>
    </header>

    <div class="flash-box">
      <% [:notice, :error, :alert].each do |level| %>
        <% unless flash[level].blank? %>
          <div class="alert <%= flash_class(level) %>">
              <%= flash[level] %>
              <%=   link_to 'x', root_path, class: 'close' %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="page-area">
      <%= yield %>
    </div>

  </div>

  <%= render 'layouts/footer' %>

  <%
  # dropdown menus and panels are defined here, and are attached to
  # their appropriate launchers by the jQuery dropdowns plugin
  %>
  <%= render 'layouts/filters_controls' %>

</body>
</html>